# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'csharp/BSOA/BSOA.sln'
  outFolder: 'csharp/BSOA/bin'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: custom
    projects: 'csharp/BSOA/**/*.csproj'
    custom: pack
    arguments: '-c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory) --include-source --include-symbols'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Binaries'
  inputs:
    PathtoPublish: '$(outFolder)'
    ArtifactName: 'build'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  displayName: 'Publish NuGet Packages'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'packages'
    publishLocation: 'Container'